export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_SNACK_MESSAGE = "GET_SNACK_MESSAGE";
export const CLEAR_SNACK_MESSAGE = "CLEAR_SNACK_MESSAGE";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const GET_CATEGORY_IMAGES = "GET_CATEGORY_IMAGES";
